name: 定期更新日历

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-ics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 仓库
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install requests icalendar

      - name: 运行脚本
        run: python scripts/run.py

      - name: 同步远程分支并处理未暂存更改
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # 1. 暂存所有更改（包括未跟踪文件）
          git stash push --include-untracked -m "ci-autostash"
          # 2. 变基拉取远端最新 main
          git pull --rebase origin main
          # 3. 恢复之前的更改
          git stash pop || echo "No stash to apply"

      - name: 提交并推送更新
        run: |
          if [ ! -f calendarIOS.ics ]; then
            echo "Error: calendarIOS.ics 未生成"
            exit 1
          fi
          if [ ! -f calendarIOS-LCK.ics ]; then
            echo "Error: calendarIOS-LCK.ics 未生成"
            exit 1
          fi
          git add calendarIOS.ics calendarIOS-LCK.ics
          git commit -m "自动更新 calendar.ics 和 calendar-LCK.ics" || \
            (git commit --amend --no-edit --date "$(date --utc)" && echo "没有变更，跳过新提交")
          # 安全强制推送，确保不会覆盖他人更新
          git push --force-with-lease
