name: 定期更新日历

# 赋予写权限以便提交改动
permissions:
  contents: write

on:
  schedule:
    # UTC 每天 0 点运行一次
    - cron: '0 0 * * *'
  workflow_dispatch:  # 支持手动触发

jobs:
  update-ics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 仓库
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          pip install requests icalendar

      - name: 运行脚本
        run: |
          python scripts/run.py

      - name: 提交并推送更新
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          if [ ! -f calendarIOS.ics ]; then
            echo "Error: calendarIOS.ics 未生成"
            exit 1
          fi

          git add calendarIOS.ics
          
          # 始终提交，不管是否有变更
          git commit -m "自动更新 calendar.ics" || (git commit --amend --no-edit --date "$(date)" && echo "没有变更，跳过新提交")
          git push
